/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package applications.rest;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertTrue("one is not two", 1 != 2);
    }
}
